// This code automatically generated by ExcelImporter

using System;
using UnityEngine;

namespace CSVConfig
{
#if UNITY_EDITOR
    [Serializable]
#endif
    public partial class Asd
    // : 
    {   
        
        /// <summary>
        /// 资源名
        /// </summary>
        public string Name;
        
        /// <summary>
        /// 是否为3D音效
        /// </summary>
        public bool Is3D;
        
        /// <summary>
        /// 是否循环
        /// </summary>
        public bool IsLoop;
        
        /// <summary>
        /// 备注
        /// </summary>
        public string Description;
        
        /// <summary>
        /// 位置
        /// </summary>
        public Vector2 Pos;
        
        
#if UNITY_EDITOR
        
#endif
        //todo
        
        
    }
}