// This code automatically generated by ExcelImporter

using System;
using UnityEngine;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace CSVConfig
{
#if UNITY_EDITOR
    [Serializable]
#endif
    public partial class Test
    // : 
    {   
        /// <summary>
        /// 音效ID  [音乐100001~199999；音效200001~299999；语音300001~399999]
        /// </summary>
        public uint Id;
        
        /// <summary>
        /// 是否为3D音效
        /// </summary>
        public bool Is3D;
        
        /// <summary>
        /// 是否循环
        /// </summary>
        public bool IsLoop;
        
        /// <summary>
        /// 备注
        /// </summary>
        public string Description;
        
        /// <summary>
        /// 位置
        /// </summary>
        public Vector2 Pos;
        
#if UNITY_EDITOR
        
        /// <summary>
        /// 资源名
        /// </summary>
        public string Name;
        
#endif
        public static List<Test> Load(TextReader reader)
        {
            var result = new List<Test>();
            //todo CSVParse 
            return result;
        }
        
    }
    
    public sealed partial class TestManager
    //: CSVManagerBase
    {
        private readonly List<Test> _dataList;
        public TestManager(TextReader reader)
        {
            _dataList = Test.Load(reader);
        }
    }
}